// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetV1CoursesData, GetV1CoursesResponses, PostV1CoursesData } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get the list of available courses
 */
export const getV1Courses = <ThrowOnError extends boolean = false>(options?: Options<GetV1CoursesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetV1CoursesResponses, unknown, ThrowOnError>({
        url: '/v1/courses',
        ...options
    });
};

/**
 * Create a new course
 */
export const postV1Courses = <ThrowOnError extends boolean = false>(options: Options<PostV1CoursesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, unknown, ThrowOnError>({
        url: '/v1/courses',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};