// This file is auto-generated by @hey-api/openapi-ts

export type _Error = {
    code?: number;
    message?: string;
};

export type CourseList = Array<Course>;

export type CoursePostRequest = {
    /**
     * The title of the course
     */
    title: string;
    /**
     * A detailed description of the course
     */
    description: string;
};

export type Course = {
    /**
     * The ID of the course
     */
    id?: string;
    /**
     * The title of the course
     */
    title?: string;
    /**
     * A detailed description of the course
     */
    description?: string;
};

export type GetV1CoursesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/courses';
};

export type GetV1CoursesResponses = {
    /**
     * Successful operation
     */
    200: CourseList;
};

export type GetV1CoursesResponse = GetV1CoursesResponses[keyof GetV1CoursesResponses];

export type PostV1CoursesData = {
    body: CoursePostRequest;
    path?: never;
    query?: never;
    url: '/v1/courses';
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};