// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zError = z.object({
    code: z.number().int().optional(),
    message: z.string().optional()
});

export const zCoursePostRequest = z.object({
    title: z.string(),
    description: z.string()
});

export const zCourse = z.object({
    id: z.string().optional(),
    title: z.string().optional(),
    description: z.string().optional()
});

/**
 * Successful operation
 */
export const zGetV1CoursesResponse = z.array(zCourse);

export const zPostV1CoursesData = zCoursePostRequest;