name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.8.0
          run_install: false

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Must call after nrwl/nx-set-shas@v4
      - name: Restore Nx Cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/.nx
            !${{ github.workspace }}/.nx/workspace-data/d
          key: nx-caches-v1-${{ env.NX_BASE }}

      - name: Copy environment config file
        shell: bash
        env:
          LOCAL_CONFIG_FILE: ${{ secrets.LOCAL_CONFIG_FILE }}
        run: |
          echo -n "$LOCAL_CONFIG_FILE" > packages/course-nosql-persistence/config/local.json
          echo -n "$LOCAL_CONFIG_FILE" > packages/course/config/local.json
    
      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - run: pnpm exec nx affected -t lint test build

      - name: Save Nx Cache
        if: github.ref == 'refs/heads/main'
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ github.workspace }}/.nx
            !${{ github.workspace }}/.nx/workspace-data/d
          key: nx-caches-v1-${{ github.sha }}